import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Header } from "./shared/components/header";
const font = Raleway({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`$${font.className} antialiased`}>
        <div className="w-full flex justify-center items-center flex-col">
          <Header/>
          {children}
        </div>
      </body>
    </html>
  );
}
